### PR TITLE
chore(deps): update @azure/functions

### PR DESCRIPTION
**Pull request by lucacavallaro**
#### List of Changes

1. Update `@azure/functions` to its latest version

#### Motivation and Context

This project used a long outdated version of `@azure/functions` which interferes with new projects that use more recent versions of the package.

#### How Has This Been Tested?

This dependence has no impact on runtime because it simply contains type definitions. Unit tests are still functional after the upgrade.

#### Types of changes

- [x] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by arcogabbo** [comment]
LGTM, should this be a minor or a patch release? I see it's a dev dependency, but 2 majors ahead could introduce some breaking changes to the types.

**Review by Garma00 — APPROVED** [review]
lgtm

**Comment by lucacavallaro** [comment]
> LGTM, should this be a minor or a patch release? I see it's a dev dependency, but 2 majors ahead could introduce some breaking changes to the types.

the types are radically different, but the part we use in this package has remained unchanged so it hasn't had an impact on the "io-functions-commons" API, so it can be released as a patch

**Comment by arcogabbo** [comment]
> > LGTM, should this be a minor or a patch release? I see it's a dev dependency, but 2 majors ahead could introduce some breaking changes to the types.
> 
> @arcogabbo the types are radically different, but the part we use in this package has remained unchanged so it hasn't had an impact on the "io-functions-commons" API, so it can be released as a patch

All fine then, thanks.

**Pull request merged**
