### PR TITLE
[#IP-320]  Migrate fp-ts version from 1.x to 2.x

### PR DESCRIPTION
**Pull request by fabriziopapi**
Update fp-ts version from 1.x to 2.x

#### List of Changes
Update fp-ts, io-ts, ts-commons and openapigen versions.
Fixed compilation errors due to different fp-ts 2.x version mode.
Fixed unit test compilation errors.

#### Motivation and Context
Reduce technical debt and enable dev to use new fp-ts feature.

#### How Has This Been Tested?

Already existing unit tests.

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by balanza — APPROVED** [review]

**Review by michaeldisaro — APPROVED** [review]
LGTM. Only a question: are all these "pipe" functions a stylistic choice to clean the code or are they the only fix to move to 2.x? (Idem for: r.isRight() that becomes E.isRight(r)).

**Comment by gquadrati** [comment]
> LGTM. Only a question: are all these "pipe" functions a stylistic choice to clean the code or are they the only fix to move to 2.x? 

It's the new construct for ...piping functions together and allowing Typescript to infer types. 
A small guide is [here](https://gcanti.github.io/fp-ts/guides/upgrade-to-v2.html), but @fabriziopapi created a more detailed guide in Confluence.

> (Idem for: r.isRight() that becomes E.isRight(r)).
`isRight` is not anymore an object method, but we need to use `Either` one.

**Comment by michaeldisaro** [comment]
Perfect. Thanks.

**Pull request merged**
