### PR TITLE
[#IP-86] tslint to eslint migration

### PR DESCRIPTION
**Pull request by michaeldisaro**
#### List of Changes
- Deleted `tslint.json` file
- Removed tslint packages from `package.json`
- Created `.eslintrc.js` configuration
- Added some lint exclusions to `.eslintrc.js` to avoid a deep refactoring of working code
- Changed tslint's "rule disabling" comments with eslint closest ones.

#### Motivation and Context
We want to migrate to eslint because tslint is deprecated.

#### How Has This Been Tested?
It has been tested by performing:
- yarn install --frozen-lockfile
- yarn build (there is an error in a middleware function not related to this PR)
- yarn lint --fix
- yarn test (all tests passed)

#### Types of changes

- [x] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by balanza — COMMENTED** [review]
Changes look good to me, however I'm seeing an over-use of escaping for `@typescript-eslint/naming-convention`. That may mean the rule doesn't fit well with out code style, we may want to review it in the `@pagopa/eslint-rules` package

Thoughts @BurnedMarshal?

**Comment by michaeldisaro** [comment]
I think it would be better to change code style not the rule. I found too
much incoherence in naming.

Il ven 9 apr 2021, 22:58 Emanuele De Cupis ***@***.***> ha
scritto:

**Comment by BurnedMarshal** [comment]
> Changes look good to me, however I'm seeing an over-use of escaping for `@typescript-eslint/naming-convention`. That may mean the rule doesn't fit well with out code style, we may want to review it in the `@pagopa/eslint-rules` package
> 
> Thoughts @BurnedMarshal?

@balanza we can extend the default rule for `@typescript-eslint/naming-convention`. Seems that this configuration could fit better the project variable naming conventions
```javascript
    "@typescript-eslint/naming-convention": [
            "error",
            // DEFAULT STRICT camelCase RULE
            {
            selector: 'default',
            format: ['camelCase'],
            leadingUnderscore: 'allow',
            trailingUnderscore: 'allow',
            },
        
            {
            selector: 'variable',
            format: ['camelCase', 'UPPER_CASE'],
            leadingUnderscore: 'allow',
            trailingUnderscore: 'allow',
            },
            {
            selector: 'typeLike',
            format: ['PascalCase'],
            },
            // EXPORTED io-ts TYPES are CamelCase
            {
                "selector": "variable",
                "format": ["PascalCase", "camelCase", "UPPER_CASE"],
                "modifiers": ["exported"]
            },
            // LOCAL io-ts TYPES (not exported)
            {
            "selector": "variable",
            "format": ["PascalCase", "UPPER_CASE"],
            "filter": {
                regex: "^.{1,}[RO]$",
                match: true
            }
        }
    ]
```
We should evaluate if we have different naming convention across several project type (functions, backend).

**Comment by balanza** [comment]
That's the way, I think. However, we must refine such definition as the following would still throw:
```ts
export const ValidationToken = t.interface({
  Email: EmailAddress,
  FiscalCode,
  InvalidAfter: UTCISODateFromString
});
```

We must include  object fields as selector

**Comment by balanza** [comment]
Commit https://github.com/pagopa/io-functions-commons/pull/139/commits/ddcf4ca11feaa1452579b60cd555cfe30dffd6b3 broke the linter intentionally - we wait for https://github.com/pagopa/eslint-rules/pull/5 and https://github.com/pagopa/eslint-rules/pull/6 to be merged and than we will inherit such rules from the central package.

**Review by balanza — APPROVED** [review]

**Pull request merged**
