### PR TITLE
Refine `ServicePreferencesSettings` type definition

### PR DESCRIPTION
**Pull request by balanza**
#### List of Changes

* `servicePreferencesSettings.version` is now either `-1` or `NonNegativeInteger`

#### Motivation and Context

This is a refinement which makes the difference between `LEGACY` and non-`LEGACY` service preferences settings more neat. 

Other than being more explicit for readers, there is no much improvement when dealing with `Profile` model alone.

On the other hand, we have benefits when using `Profile` model alongside `ServicePreference`. As `ServicePreference.settingsVersion` is defined as `NonNegativeInteger`, it is now _impossible_ to create a `ServicePreference` from a `Profile` working in `LEGACY` mode, which is a domain concept now constrained into the type system.

**Please note that this PR must be merged before we have profiles with `servicePreferencesSettings` in production**, as values are not compatible with what's before.

#### How Has This Been Tested?

Integration tests

#### Types of changes

- [x] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by BurnedMarshal — APPROVED** [review]
LGTM

**Comment by michaeldisaro** [comment]
Be carefull that integration tests are broken.

**Review by gquadrati — APPROVED** [review]
Looks good to me too

**Comment by balanza** [comment]
> IMHO the only thing that should happen is that non legacy versions start from 0 instead of 1.

What do you mean?

**Pull request merged**
