### PR TITLE
[#IP-379] Replaced StrMap with ReadonlyMap

### PR DESCRIPTION
**Pull request by michaeldisaro**
#### List of Changes
Replaced StrMap with ReadonlyMap because it's been removed from fp-ts 2.x

#### Motivation and Context
Upgrade to fp-ts 2.x

#### How Has This Been Tested?
* yarn test

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by gquadrati — APPROVED** [review]
LGTM

**Comment by balanza** [comment]
Both functions have no test coverage at all. It was so even before the `fp-ts` porting, so I don't feel like it's this PR's lack. Anyway I felt like adding some in https://github.com/pagopa/io-functions-commons/pull/202/commits/b77a4ccfa908d9e46d4d2a71802c6b22172a4029, please review they make sense and feel free to add some more scenarios if you're fancy to.

**Comment by michaeldisaro** [comment]
> Both functions have no test coverage at all.
Oh, you're right. I missed that. Well done for adding new tests, I'll check them.

**Review by gquadrati — APPROVED** [review]
LGTM

**Pull request merged**
